export const SUBJECTS = [
  'Art','Biography','Biology','Chemistry','Crafts','Crime','Diary','Drama',
  'Economics','Fiction','Food','History','Geography','Humor','Language',
  'Math','Medicine','Misc','Music','Mythology','Nature','Neuroscience','Philosophy',
  'Photography','Physics','Poetry','Politics','Psychology','Religion','Reportage',
   'Rights','Science','Science Fiction','Sociology','Sport','Technology','Travel','War'
];

// Keyword → subject mapping: raw subject words from APIs → our category
export const SUBJECT_KEYWORDS = {
  'Art':             ['art','painting','sculpture','drawing','illustration','design','architecture','museum','gallery',
                      'arte','pittura','scultura','disegno','illustrazione','architettura','museo','galleria'],
  'Astro':           ['Astronomy', 'Astrophysics', 'Space', 'Stellar',
                      'astronomia','astrofisica','spazio','stellare'],
  'Biography':       ['biography','autobio','memoir','life of','personal narrative','diary','personal history',
                      'biografia','autobiografia','memorie','vita di','narrativa personale','diario','storia personale'],
  'Biology':         ['biology','botany','zoology','ecology','microbiology','evolution','life science','organism',
                      'biologia','botanica','zoologia','ecologia','microbiologia','evoluzione','scienze della vita','organismo'],
  'Chemistry':       ['chemistry','atom','reaction','molecule',
                      'chimica','atomo','reazione','molecola'],
  'Crafts':          ['craft','knitting','sewing','woodwork','pottery','diy','handmade','hobby',
                      'artigianato','lavoro a maglia','cucito','falegnameria','ceramica','fatto a mano'],
  'Crime':           ['crime','detective','mystery','thriller','noir','murder','investigation','police','forensic',
                      'crimine','giallo','mistero','omicidio','indagine','polizia','investigazione','delitto'],
  'Diary':           ['diary','journal','letters','correspondence','personal',
                      'diario','giornale','lettere','corrispondenza','personale','epistolario'],
  'Drama':           ['drama','play','theatre','theater','playwriting','screenplay','script',
                      'dramma','commedia','teatro','sceneggiatura','copione','opera teatrale'],
  'Economics':       ['economics','economy','finance','business','trade','market','capitalism','monetary','banking','investment',
                      'economia','finanza','affari','commercio','mercato','capitalismo','monetario','banca','investimento'],
  'Fiction':         ['fiction','novel','short stories','literary','narrative','story','tales',
                      'narrativa','romanzo','racconti','letterario','racconto','storie','novella'],
  'Food':            ['food','cooking','gastronomy','cuisine','recipe','chef','culinary','nutrition',
                      'cibo','cucina','gastronomia','ricetta','culinario','nutrizione','alimentazione'],
  'Genetics':        ['genetics','genome','genomics','heredity','dna','gene','inheritance','trait','mutation','chromosome',
                      'genetica','genoma','genomica','ereditarietà','gene','eredità','tratto','mutazione','cromosoma'],
  'Geography':       ['geography','cartography','map','region','landscape','territory','place',
                      'geografia','cartografia','mappa','regione','paesaggio','territorio','luogo'],
  'History':         ['history','historical','ancient','medieval','modern history','world war','civilization','heritage',
                      'storia','storico','antico','medievale','storia moderna','guerra mondiale','civiltà','patrimonio'],
  'Humor':           ['humor','humour','comedy','satire','parody','wit','funny','comic',
                      'umorismo','commedia','satira','parodia','divertente','comico','spiritoso'],
  'Language':        ['language','linguistics','grammar','etymology','dictionary','philology','translation','lexicon',
                      'lingua','linguistica','grammatica','etimologia','dizionario','filologia','traduzione','lessico'],
  'Logic':           ['logic','formal logic','reasoning','deduction','induction','inference','argument','predicate','proposition','syllogism',
                      'logica','logica formale','ragionamento','deduzione','induzione','inferenza','argomento','predicato','proposizione','sillogismo'],
  'Math':            ['math','mathematics','algebra','geometry','calculus','statistics','probability','number theory',
                      'matematica','algebra','geometria','calcolo','statistica','probabilità','teoria dei numeri'],
  'Medicine':        ['medicine','medical','health','disease','anatomy','physiology','clinical','surgery','pharmacy','psychiatry',
                      'medicina','medico','salute','malattia','anatomia','fisiologia','clinico','chirurgia','farmacia','psichiatria'],
  'Misc':            ['miscellaneous','general','reference','collection',
                      'vario','generale','riferimento','collezione','raccolta'],
  'Music':           ['music','musicology','composition','jazz','classical','opera','rock','song','instrument',
                      'musica','musicologia','composizione','classica','canzone','strumento'],
  'Mythology':       ['mythology','myth','legend','folklore','fairy tale','epic','fable',
                      'mitologia','mito','leggenda','folclore','fiaba','epica','favola'],
  'Nature':          ['nature','environment','wildlife','plants','animals','natural world','conservation','outdoor',
                      'natura','ambiente','fauna selvatica','piante','animali','mondo naturale','conservazione'],
  'Neuroscience':    ['neuroscience','neurology','brain','cognition','neural','consciousness','cognitive science',
                      'neuroscienze','neurologia','cervello','cognizione','neurale','coscienza','scienze cognitive'],
  'Philosophy':      ['philosophy','ethics','metaphysics','epistemology','phenomenology','aesthetics','moral',
                      'filosofia','etica','metafisica','epistemologia','fenomenologia','estetica','morale'],
  'Photography':     ['photography','photo','photographic','camera',
                      'fotografia','foto','fotografico','macchina fotografica'],
  'Physics':         ['physics','quantum','mechanics','thermodynamics','relativity','electromagnetism','optics','astrophysics',
                      'fisica','quantistica','meccanica','termodinamica','relatività','elettromagnetismo','ottica','astrofisica'],
  'Poetry':          ['poetry','poem','verse','lyric','haiku','sonnet',
                      'poesia','poema','verso','lirica','sonetto'],
  'Politics':        ['politics','political','government','democracy','law','diplomacy','international relations','policy',
                      'politica','politico','governo','democrazia','legge','diplomazia','relazioni internazionali','diritto'],
  'Psychology':      ['psychology','psychoanalysis','behavior','mental','personality','developmental','social psychology',
                      'psicologia','psicoanalisi','comportamento','mentale','personalità','psicologia sociale','psicologia dello sviluppo'],
  'Religion':        ['religion','theology','spirituality','bible','quran','buddhism','christianity','islam','faith','sacred',
                      'religione','teologia','spiritualità','bibbia','corano','buddismo','cristianesimo','fede','sacro'],
  'Reportage':       ['journalism','reportage','report','news','investigative','documentary','nonfiction narrative',
                      'giornalismo','reportage','inchiesta','notizie','documentario','narrativa non fiction'],
  'Rights':          ['rights','human rights','civil rights','civil liberties','justice','equality','freedom','constitution','legal','suffrage',
                      'diritti','diritti umani','diritti civili','libertà civili','giustizia','uguaglianza','libertà','costituzione','legale','suffragio'],
  'Science':         ['science','scientific','geology','earth science',
                      'scienza','scientifico','geologia','scienze della terra'],
  'Science Fiction': ['science fiction','sci-fi','sci fi','speculative','dystopia','utopia','cyberpunk','space opera','futuristic',
                      'fantascienza','speculativo','distopia','utopia','futuristico','opera spaziale'],
  'Sociology':       ['sociology','society','culture','anthropology','social','community','ethnography',
                      'sociologia','società','cultura','antropologia','sociale','comunità','etnografia'],
  'Sport':           ['sport','sports','athletics','football','basketball','tennis','running','cycling','swimming','fitness',
                      'atletica','calcio','pallacanestro','corsa','ciclismo','nuoto'],
  'Technology':      ['technology','engineering','computer','software','hardware','programming','internet','artificial intelligence','robotics',
                      'tecnologia','ingegneria','informatica','programmazione','intelligenza artificiale','robotica'],
  'Travel':          ['travel','voyage','journey','exploration','adventure','travelogue','guide','tourism',
                      'viaggio','avventura','esplorazione','turismo','guida','pellegrinaggio'],
  'War':             ['war','military','battle','conflict','army','navy','air force','soldier','combat','weaponry',
                      'guerra','militare','battaglia','conflitto','esercito','marina','aeronautica','soldato','combattimento','armi'],
};

export const LANG_LABELS = {
  it: 'Italian', en: 'English', es: 'Spanish', fr: 'French'
};
